### ISSUE TITLE
Navigating to routes give compilation error

### ISSUE THREAD

**Issue by SteveWarwick** [ardalis/AspNetCoreRouteDebugger#2]
I tried to drop in these files to my 'Pages' folder. However, when I attempted to start my application it's giving me the following errors. I'm using a standard .NET Core 2.0 MVC Web App template and not the Pages one. I made sure PreserveCompiliationContext was set to true. Is there something else I need to change to get this working?

> An error occurred during the compilation of a resource required to process this request. Please review the following specific error details and modify your source code appropriately.
> Generated Code
> One or more compilation references are missing. Ensure that your project is referencing 'Microsoft.NET.Sdk.Web' and the 'PreserveCompilationContext' property is not set to false.
> 
> The type or namespace name 'RoutesModel' could not be found (are you missing a using directive or an assembly reference?)
> +
>         public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<RoutesModel> Html { get; private set; }
> The type or namespace name 'RoutesModel' could not be found (are you missing a using directive or an assembly reference?)
> +
>         public global::Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary<RoutesModel> ViewData => (global::Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary<RoutesModel>)PageContext?.ViewData;
> The type or namespace name 'RoutesModel' could not be found (are you missing a using directive or an assembly reference?)
> +
>         public RoutesModel Model => ViewData.Model;
> The type or namespace name 'RoutesModel' could not be found (are you missing a using directive or an assembly reference?)
> +
>         public global::Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary<RoutesModel> ViewData => (global::Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary<RoutesModel>)PageContext?.ViewData;
>

**Comment by ardalis** [comment]
I'm out of office this week but will try to help diagnose the issue next week.

**Comment by salvador-guerrero** [comment]
I solved this by adding the following line after ```@page```

    @using RouteDebugging.Pages

**Comment by ardalis** [comment]
Fixed now
