### ISSUE TITLE
Fails for razor pages

### ISSUE THREAD

**Issue by expressiveco** [ardalis/AspNetCoreRouteDebugger#5]
It fails for razor pages. Please check my fork that supports both razor pages and views.

[Routes.cshtml](https://github.com/expressiveco/AspNetCoreRouteDebugger/blob/master/RouteDebuggerPage/Routes.cshtml)

[Routes.cshtml.cs](https://github.com/expressiveco/AspNetCoreRouteDebugger/blob/master/RouteDebuggerPage/Routes.cshtml.cs)

**Comment by ardalis** [comment]
Fixed now, thanks!
